config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  namespace :site do
    get 'home', to: 'home#index'
    get 'search', to: 'search#ads'

    namespace :profile do
      resources :dashboard, only: %i[index]
      resources :ads, only: %i[index edit update new create]
      resources :member, only: %i[edit update]
    end

    resources :ad_details, only: %i[show]
    resources :categories, only: %i[show]
    resources :comments, only: %i[create]
  end

  namespace :checkout do
    resources :payments, only: %i[create]
  end

  get 'backoffice', to: 'backoffice/dashboard#index'
  namespace :backoffice do
    get 'dashboard', to: 'dashboard#index'
    resources :send_email, only: %i[edit create]
    resources :admins, except: %i[show]
    resources :categories, except: %i[show destroy]
    resources :diagrams, only: %i[index]
  end
  devise_for :admins, skip: [:registrations]
  devise_for :members, controllers: { sessions: 'members/sessions', registrations: 'members/registrations'}
  root 'site/home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/backoffice/admins_controller.rb
class Backoffice::AdminsController < BackofficeController
  before_action :set_admin, only: %i[edit update destroy]
  after_action :verify_authorized, only: %i[new destroy]
  after_action :verify_policy_scoped, only: :index

  def index
    @admins = policy_scope(Admin)
  end

  def new
    @admin = Admin.new
    authorize @admin
  end

  def create
    @admin = Admin.new(admin_params)
    if @admin.save
      redirect_to backoffice_admins_path, notice: I18n.t('messages.created_with', item: @admin.first_name)
    else
      render :new, notice: 'Erro ao salvar administrador'
    end
  end

  def edit
  end

  def update
    if @admin.update(admin_params)
      AdminMailer.update_email(current_user, @admin).deliver_now
      redirect_to backoffice_admins_path, notice: "A Administrador #{@admin.first_name} foi atualizado com sucesso!"
    else
      render :edit, notice: 'Erro ao atualizar administrador'
    end
  end

  def destroy
    authorize @admin
    if @admin.destroy
      redirect_to backoffice_admins_path, notice: 'Administador excluído com sucesso.'
    else
      redirect_to backoffice_admins_path, notice: 'Erro ao excluir administrador'
    end
  end

  private

  def set_admin
    @admin = Admin.find(params[:id])
  end

  def admin_params
    if password_blank?
      params[:admin].extract!(:password, :password_confirmation)
    end

    if @admin.blank?
      params.require(:admin).permit(:first_name, :last_name, :email, :role, :password,
                                    :password_confirmation)
    else
      params.require(:admin).permit(policy(@admin).permitted_attributes)
    end
  end

  def password_blank?
    params[:admin][:password].blank? &&
    params[:admin][:password_confirmation].blank?
  end
end

app/controllers/backoffice/categories_controller.rb
class Backoffice::CategoriesController < BackofficeController
  before_action :set_category, only: %i[edit update]

  def index
    @categories = Category.order(description: :asc)
  end

  def new
    @category = Category.new
  end

  def create
    @category = CategoryService.create(category_params)
    if @category.errors.any?
      render :new, notice: 'Erro ao salvar categoria'
    else
      redirect_to backoffice_categories_path, notice: "A Categoria  #{@category.description} foi cadastrada com sucesso!"
    end
  end

  def edit
  end

  def update
    if @category.update(category_params)
      redirect_to backoffice_categories_path, notice: "A Categoria #{@category.description} foi atualizada com sucesso!"
    else
      render :edit, notice: 'Erro ao atualizar categoria'
    end
  end

  private

  def set_category
    @category = Category.friendly.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:description)
  end
end

app/controllers/backoffice/dashboard_controller.rb
class Backoffice::DashboardController < BackofficeController
  def index; end
end

app/controllers/backoffice/diagrams_controller.rb
class Backoffice::DiagramsController < BackofficeController
  def index
    %x(bundle exec erd --filename='public/diagram')
  end
end

app/controllers/backoffice/send_email_controller.rb
class Backoffice::SendEmailController < ApplicationController
  def edit
    @admin = Admin.find(params[:id])
    respond_to do |format|
      format.js
    end
  end

  def create
    begin
      AdminMailer.send_message(current_admin, params[:'recipient-email'], params[:'subject-text'], params[:'message-text']).deliver_now
      @notify_message = 'E-mail enviado com sucesso!'
      @notify_flag = 'success'
    rescue StandardError => e
      @notify_message = 'Erro ao enviar e-mail. Tente novamente'
      @notify_flag = 'error'
    end

    respond_to do |format|
      format.js
    end
  end
end

app/controllers/backoffice_controller.rb
class BackofficeController < ApplicationController
  before_action :authenticate_admin!

  layout 'backoffice'
end

app/helpers/backoffice/admins_helper.rb
module Backoffice::AdminsHelper
  OptionsForRoles = Struct.new(:id, :description)

  def options_for_roles
    Admin.roles_i18n.map do |key, value|
      OptionsForRoles.new(key, value)
    end
  end
end

app/helpers/backoffice/categories_helper.rb
module Backoffice::CategoriesHelper
end

app/helpers/backoffice/dashboard_helper.rb
module Backoffice::DashboardHelper
end

app/helpers/backoffice/diagrams_helper.rb
module Backoffice::DiagramsHelper
end

app/helpers/backoffice/send_email_helper.rb
module Backoffice::SendEmailHelper
end

app/views/backoffice/admins/edit.html.erb
<%= render partial: 'backoffice/admins/shared/form', locals: { action: 'Editando Administrador'} %>

app/views/backoffice/admins/index.html.erb
 <div class="container-fluid px-4">
 <h1 class="mt-4">Administradores</h1>
  <ol class="breadcrumb mb-4">
    <li class="breadcrumb-item active">Listando Administradores</li>
  </ol>
<div class="card mb-4">
  <div class="card-header">
      <i class="fas fa-list"></i>
      Listando Administradores

      <div class="d-grid gap-2 d-md-flex justify-content-md-end">
        <% if policy(@admins).new? %>
          <%= link_to new_backoffice_admin_path, class: "btn btn-success me-md-2" do %>
            Novo Administrador
          <% end %>
        <% end %>
      </div>
  </div>
  <div class="card-body">
            <table id="datatablesSimple">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Nome</th>
                        <th>E-mail</th>
                        <th>Tipo de acesso</th>
                        <th></th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th>#</th>
                        <th>Descrição</th>
                    </tr>
                </tfoot>
                <tbody>
                  <% @admins.each do |admin| %>
                    <tr>
                        <td><%= admin.id %></td>
                        <td><%= admin.full_name %></td>
                        <td><%= admin.email %></td>
                        <td><%= admin.role_i18n %></td>
                        <td style="width: 170px;">
                          <%= link_to edit_backoffice_send_email_path(admin.id), class: 'btn btn-secondary',
                          remote: true do %>
                              <i class="fa fa-envelope"></i>
                          <% end %>
                          <%= link_to edit_backoffice_admin_path(admin.id), class: "btn btn-primary" do %>
                              <i class="fa fa-edit"></i>
                          <% end %>
                          <% if current_admin.id != admin.id &&
                             policy(admin).destroy? %>
                            <%= link_to backoffice_admin_path(admin.id), method: :delete, class: 'btn btn-danger',
                            data: {confirm_swal: I18n.t('messages.confirm_with', item: admin.first_name ) } do %>
                                <i class="fa fa-trash"></i>
                            <% end %>
                          <% else %>
                             <button type="button" class="btn btn-danger" disabled="true">
                                <i class="fa fa-trash"></i>
                              </button>
                          <% end %>
                        </td>
                    </tr>
                  <% end %>
                </tbody>
            </table>
        </div>
  </div>
</div>

<%= render partial: 'backoffice/admins/shared/send_email' %>

app/views/backoffice/admins/new.html.erb
<%= render partial: 'backoffice/admins/shared/form', locals: { action: 'Novo Administrador'} %>