config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  namespace :site do
    get 'home', to: 'home#index'
    get 'search', to: 'search#ads'

    namespace :profile do
      resources :dashboard, only: %i[index]
      resources :ads, only: %i[index edit update new create]
      resources :member, only: %i[edit update]
    end

    resources :ad_details, only: %i[show]
    resources :categories, only: %i[show]
    resources :comments, only: %i[create]
  end

  namespace :checkout do
    resources :payments, only: %i[create]
  end

  get 'backoffice', to: 'backoffice/dashboard#index'
  namespace :backoffice do
    get 'dashboard', to: 'dashboard#index'
    resources :send_email, only: %i[edit create]
    resources :admins, except: %i[show]
    resources :categories, except: %i[show destroy]
    resources :diagrams, only: %i[index]
  end
  devise_for :admins, skip: [:registrations]
  devise_for :members, controllers: { sessions: 'members/sessions', registrations: 'members/registrations'}
  root 'site/home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ad.rb
class Ad < ApplicationRecord
  # ratyRate gem
  ratyrate_rateable 'quality'
  # Callbacks
  before_save :md_to_html

  # Enum
  enum status: %i[active processing sold]

  # Relationships
  belongs_to :category, counter_cache: true
  belongs_to :member
  has_many :comments

  # validates
  validates :member, :category, :picture, :finish_date, presence: true
  validates :description_md, :description_short, :title, presence: true
  validates :price, numericality: { greater_than: 0 }

  # Scopes
  scope :descending_order, ->(quantity = 8, page) { order(created_at: :desc).page(page).per(quantity) }
  scope :member_ads, ->(current_member) { where(member: current_member).order(created_at: :desc) }
  scope :where_category, ->(id) { where(category_id: id).order(title: :asc) }
  scope :search, ->(q, page) { where("lower(title) LIKE ?", "%#{q.downcase}%").page(page).per(8) }

  # Active storage image
  has_one_attached :picture do |attached|
    attached.variant :thumb, resize_to_limit: [100, 100]
  end

  # gem money_rails
  monetize :price_cents

  private
  def md_to_html
    options = {
      filter_html: true,
      link_attributes: {
        rel: "nofollow",
        target: "_blank"
      }
    }

    extensions = {
      space_after_headers: true,
      autolink: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    self.description = markdown.render(self.description_md).html_safe
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  # Scopes
  scope :with_full_access, -> { where(role: :full_access) }
  scope :with_restricted_access, -> { where(role: :restricted_access) }

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :trackable

  # Enums
  enum role: %i[full_access restricted_access]

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "Member"
  belongs_to :rateable, :polymorphic => true
end

app/models/category.rb
class Category < ApplicationRecord
  # Gem Friendly Id
  include FriendlyId
  friendly_id :description, use: :slugged
  # Relationships
  has_many :ads

  # Validations 
  validates_presence_of :description

  # Scopes
  scope :order_by_description, -> { order(:description) }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :member
  belongs_to :ad
end

app/models/member.rb
class Member < ApplicationRecord
  # Ratyrate gem
  ratyrate_rater

  # Associations
  has_many :ads

  validates_presence_of :first_name, message: 'não pode ficar em branco'
  validates_presence_of :last_name, message: 'não pode ficar em branco'

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :trackable

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :ad
  belongs_to :buyer, class_name: 'Member'

  enum status: %i[requested waiting analysing paid avaliable dispute returned canceled]
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "Member"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Pundit
  include Pundit::Authorization

  # Set Layout
  layout :layout_by_resource

  # Managers Pundit Not authorized error
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  def current_user
    return current_member if current_member.present?

    current_admin
  end

  private

  def user_not_authorized
    flash[:alert] = 'Você não tem permissão para realizar esta ação'
    redirect_back(fallback_location: backoffice_path)
  end

  def layout_by_resource
    if devise_controller? && resource_name == :admin
      'backoffice_devise'
    elsif devise_controller? && resource_name == :member
      'site_devise'
    else
      'application'
    end
  end
end

app/controllers/backoffice_controller.rb
class BackofficeController < ApplicationController
  before_action :authenticate_admin!

  layout 'backoffice'
end

app/controllers/rater_controller.rb
class RaterController < ApplicationController

  def create
    if member_signed_in?
      obj = params[:klass].classify.constantize.find(params[:id])
      obj.rate params[:score].to_f, current_member, params[:dimension]

      render :json => true
    else
      render :json => false
    end
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  before_action :store_user_location!, if: :storable_location?
  before_action :set_categories
  layout 'site'


  private

  def set_categories
    @categories = Category.order_by_description
  end

  def storable_location?
    request.get? && is_navigational_format? && !devise_controller? && !request.xhr? 
  end

  def store_user_location!
    # :user is the scope we are authenticating
    store_location_for(:member, request.fullpath)
  end
end

app/helpers/ad_details_helper.rb
module AdDetailsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    current_member
  end
end

app/helpers/site/comments_helper.rb
module Site::CommentsHelper
end

app/helpers/site/home_helper.rb
module Site::HomeHelper
end

app/helpers/site/search_helper.rb
module Site::SearchHelper
end

app/views/backoffice/admins/shared/_form.html.erb
 <div class="container-fluid px-4">
 <h1 class="mt-4">Categorias</h1>
  <ol class="breadcrumb mb-4">
    <li class="breadcrumb-item active"> <%= action %> </li>
  </ol>

 <% if @admin.errors.any? %>
    <% @admin.errors.full_messages.each do |message| %>
      <script>
        $.notify( '<%= message %>' , "error");
      </script>
    <% end %>
  <% end %>

  <div class="card mb-4">
    <div class="card-header">
      <% if action == 'Novo Administrador' %>
        <i class="fas fa-plus"></i>
      <% else %>
        <i class="fas fa-edit"></i>
      <% end %>
        <%= action %>
    </div>

 <div class="card-body">
    <div class="col-lg-6">
      <%= form_for([:backoffice, @admin]) do |f| %>
        <div class="form-group">
          <label>Nome</label>
          <%= f.text_field :first_name, class:'form-control', placeholder: 'Nome' %>
        </div>
        <div class="form-group">
          <label>Sobrenome</label>
          <%= f.text_field :last_name, class:'form-control', placeholder: 'Sobrenome' %>
        </div>
        <div class="form-group">
          <label>Email</label>
          <%= f.email_field :email, class:'form-control', placeholder: 'exemplo@gmail.com' %>
        </div>
        <div class="form-group">
          <label>Senha</label>
          <%= f.password_field :password, class:'form-control', placeholder: 'Senha' %>
        </div>
        <div class="form-group">
          <label>Confirmação de senha</label>
          <%= f.password_field :password_confirmation, class:'form-control', placeholder: 'Confirmação de senha' %>
        </div>
        <br>
        <% if policy(@admin).edit? %>
          <div class="form-group">
            <b><label>Tipo de acesso</label></b>
            <%= f.collection_radio_buttons(:role, options_for_roles, :id, :description) do |b| %>
              <div class ="radio">
                <label>
                  <%= b.label { b.radio_button + b.text } %>
                </label>
              </div>
            <% end %>
          </div>
        <% end %>
        <button type="submit" class="btn btn-primary" style="margin-top: 10px;">
        Enviar </button>
      <% end %>
    </div>
  </div>
</div>

app/views/backoffice/admins/shared/_send_email.html.erb
<div class="modal fade" id="sendEmail" tabindex="-1" role="dialog" aria-labelledby="sendEmailModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">New message</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_tag(backoffice_send_email_index_path, remote: true) do %>
          <div class="form-group">
            <label for="recipient-email" class="col-form-label">Recipient:</label>
            <%= text_field_tag(:'recipient-email', nil, class: 'form-control', readonly: 'readonly') %>
          </div>
          <div class="form-group">
            <label for="subject-text" class="col-form-label">Assunto:</label>
            <%= text_field_tag(:'subject-text', nil, class: 'form-control') %>
          </div>
          <div class="form-group">
            <label for="message-text" class="col-form-label">Message:</label>
            <%= text_area_tag(:'message-text', nil, class: 'form-control') %>
          </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <%= submit_tag 'Send Message', class: 'btn btn-primary'%>
        </div>
      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/shared/_notifications.html.erb
<% if notice %>
    <%= javascript_tag "$.notify('#{notice}', { className: 'success', 
    globalPosition: 'right bottom' });" %>
<% end %>
<% if alert %>
  <script>
    $.notify('<%= alert %>', { className: 'error',
    globalPosition: 'right bottom' });
  </script>
<% end %>